<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run()
    {

        $countries = [
            'Afghanistan',
            'Albania',
            'Algeria',
            'Andorra',
            'Angola',
            'Antigua',
            'Argentina',
            'Armenia',
            'Australia',
            'Austria',
            'Austrian Empire',
            'Azerbaijan',
            'Baden',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Bavaria',
            'Belarus',
            'Belgium',
            'Belize',
            'Benin',
            'Bolivia',
            'Bosnia',
            'Botswana',
            'Brazil',
            'Brunei',
            'Brunswick',
            'Bulgaria',
            'Burkina Faso',
            'Burma',
            'Burundi',
            'Cabo Verde',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Cayman Islands',
            'Central African Republic',
            'Central American Federation',
            'Chad',
            'Chile',
            'China',
            'Colombia',
            'Comoros',
            'Congo Free State',
            ' Costa Rica',
            'Cote',
            'Croatia',
            'Cuba',
            'Cyprus',
            'Czechia',
            'Czechoslovakia',
            'Democratic Republic of the Congo',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'Duchy of Parma',
            'East Germany',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guinea',
            'Eritrea',
            'Estonia',
            'Eswatini',
            'Ethiopia',
            'Federal Government of Germany',
            'Fiji',
            'Finland',
            'France',
            'Gabon',
            'Gambia',
            'Georgia',
            'Germany',
            'Ghana',
            'Grand Duchy of Tuscany',
            'Greece',
            'Grenada',
            'Guatemala',
            'Guinea',
            'Guyana',
            'Haiti',
            'Hanover',
            'Hanseatic Republics',
            'Hawaii',
            'Hesse',
            'Holy See',
            'Honduras',
            'Hungary',
            'Iceland',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland',
            'Israel',
            'Italy',
            'Jamaica',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Korea',
            'Kosovo',
            'Kuwait',
            'Kyrgyzstan',
            'Laos',
            'Latvia',
            'Lebanon',
            'Lesotho',
            'Lew Chew',
            'Liberia',
            'Libya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Marshall Islands',
            'Mauritania',
            'Mauritius',
            'Mecklenburg',
            'Mexico',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Morocco',
            'Mozambique',
            'Namibia',
            'Nassau',
            'Nauru',
            'Nepal',
            'Netherlands',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'North German Confederation',
            'North German Union',
            'North Macedonia',
            'Norway',
            'Oldenburg',
            'Oman',
            'Orange Free State',
            'Pakistan',
            'Palau',
            'Panama',
            'Papal States',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Piedmont',
            'Poland',
            'Portugal',
            'Qatar',
            'Republic of Genoa',
            'Republic of Korea',
            'Republic of the Congo',
            'Romania',
            'Russia',
            'Rwanda',
            'Saint Kitts ',
            'Saint Lucia',
            'Saint Vincent',
            'Samoa',
            'San Marino',
            'Sao Tome ',
            'Saudi Arabia',
            'Schaumburg-Lippe',
            'Senegal',
            'Serbia',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Slovakia',
            'Slovenia',
            'Solomon Islands',
            'Somalia',
            'South Africa',
            'South Sudan',
            'Spain',
            'Sri Lanka',
            'Sudan',
            'Suriname',
            'Sweden',
            'Switzerland',
            'Syria',
            'Tajikistan',
            'Tanzania',
            'Texas',
            'Thailand',
            'Timor-Leste',
            'Togo',
            'Tonga',
            'Trinidad',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Tuvalu',
            'Two Sicilies',
            'Uganda',
            'Ukraine',
            'Union of Soviet Socialist Republics',
            'United Arab Emirates',
            ' United Kingdom',
            'Uruguay',
            'Uzbekistan',
            'Vanuatu',
            'Venezuela',
            'Vietnam',
            'Württemberg',
            'Yemen',
            'Zambia',
            'Zimbabwe',
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name' => $country,
            ]);
        }
    }
}
